-- MySQL Script generated by MySQL Workbench
-- Sat Feb 11 15:53:26 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `client` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cargo` (
  `id_cargo` INT NOT NULL AUTO_INCREMENT,
  `weight` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Truck`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Truck` (
  `id_truck` INT NOT NULL AUTO_INCREMENT,
  `numb` VARCHAR(6) NOT NULL,
  `Driver` VARCHAR(45) NULL,
  PRIMARY KEY (`id_truck`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`City` (
  `id_city` INT NOT NULL AUTO_INCREMENT,
  `city_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_city`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Delivery` (
  `id_delivery` INT NOT NULL AUTO_INCREMENT,
  `client` INT NOT NULL,
  `cargo` INT NOT NULL,
  `truck` INT NOT NULL,
  `city` INT NOT NULL,
  `date_delivery` DATETIME NOT NULL,
  PRIMARY KEY (`id_delivery`),
  INDEX `client_idx` (`client` ASC) VISIBLE,
  INDEX `cargo_idx` (`cargo` ASC) VISIBLE,
  INDEX `truck_idx` (`truck` ASC) VISIBLE,
  INDEX `city_idx` (`city` ASC) VISIBLE,
  CONSTRAINT `client`
    FOREIGN KEY (`client`)
    REFERENCES `mydb`.`Clients` (`id_client`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cargo`
    FOREIGN KEY (`cargo`)
    REFERENCES `mydb`.`Cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `truck`
    FOREIGN KEY (`truck`)
    REFERENCES `mydb`.`Truck` (`id_truck`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `city`
    FOREIGN KEY (`city`)
    REFERENCES `mydb`.`City` (`id_city`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
